name: flutter_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-94.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  chewie: ^1.5.0
  video_player: ^2.6.1
  http: ^0.13.6
  day_night_switcher: ^0.2.0+1
  flutter_modular: ^5.0.3
  firebase_core: ^2.13.0
  flutter_animate: ^4.1.1+1
  firebase_auth: ^4.6.1
  flutter_svg: ^2.0.6
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-Black.ttf
          weight: 900

        - asset: assets/fonts/Alegreya-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Alegreya-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Alegreya-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Alegreya-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alegreya-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Alegreya-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Alegreya-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Alegreya-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alegreya-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Alegreya-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alegreya-Italic.ttf
          style: italic
          weight: 400
          