name: flutter_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-94.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  shared_preferences: ^2.1.1
  chewie: ^1.5.0
  video_player: ^2.6.1
  http: ^0.13.6
  day_night_switcher: ^0.2.0+1
  flutter_modular: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Electrolize
      fonts:
        - asset: assets/fonts/Electrolize-Regular.ttf
